#165377507 Update READ.me to Include setup Instructions
andela/apollo-ah-frontend pull request #16
Opened 2019-04-16 11:18 UTC by fejiroofficial

#### What does this PR do?
- updates the readme file to include a description for the project set up

#### Description of Task to be completed?
- add the description for the set up to the repository

#### What are the relevant pivotal tracker stories?
[#165377507](https://www.pivotaltracker.com/story/show/165377507)

2019-04-16 12:39 UTC, aanchirinah requested changes
Good job @fejiroofficial , kindly attend to my requested changes.

2019-04-16 12:39 UTC, aanchirinah commented on README.md
> +FACEBOOK_AUTH_URL=
#### Nitpick
- We can add a `.env.example` reference to this

2019-04-16 12:39 UTC, aanchirinah commented on README.md
> +```
#### Nitpick
- List the features of the application and indicate those that work now.

2019-04-16 18:04 UTC, thislekan commented
Is this PR ready or are we still implementing feedback? @fejiroofficial

2019-05-03 09:15 UTC, aanchirinah requested changes
Nice job but review my changes.

2019-05-03 09:15 UTC, aanchirinah commented on README.md
> +FACEBOOK_AUTH_URL=http://localhost:3000/api/v1/auth/facebook
#### Nitpick
```suggestion
FACEBOOK_AUTH_URL=http://localhost:<PORT_NUMBER>/api/v1/auth/facebook
```

2019-05-04 12:59 UTC, valenstical approved these changes
LGTM

2019-05-07 10:57 UTC, davdwhyte87 approved these changes
LGTM

2019-05-07 11:36 UTC, devdbrandy approved these changes
Looks good to me.

2019-05-22 09:28 UTC, closed without merging