#165250447 Article categories
andela/apollo-ah-frontend pull request #20
Opened 2019-04-17 14:08 UTC by Andraquin

#### What does this PR do?
It creates article categories page

#### Description of task to be completed?
- write test for category page
- create category component
- build out category page

#### How should this be manually tested?
- Follow the steps below:
  - Run the following commands in your terminal
`git clone https://github.com/andela/apollo-ah-frontend.git`
`cd apollo-ah-frontend`
- Run `npm install` to install all dependencies.
- Start the app 
#### What are the relevant pivotal tracker stories?
[#165250447](https://www.pivotaltracker.com/story/show/165250447)
#### Screenshots (if appropriate)
![articleCategory](https://user-images.githubusercontent.com/44200495/56294100-45d6d400-6122-11e9-85dd-43c587979f91.gif)

#### Questions:

2019-04-18 08:28 UTC, fejiroofficial commented
You have a host of conflicts to resolve @Andraquin.

2019-04-21 06:24 UTC, valenstical commented on src/selectors/categorySelector.js
> +const categorySelector = state => state.articlesCategoryReducer.category;
```suggestion
const categorySelector = state => state.categories;
```
Then in the combineReducer, we can have,
`{
  categories: articleCategoryReducer
}`

What do you think?

2019-04-21 06:26 UTC, valenstical commented on src/selectors/categorySelector.js
> +const categoryIsLoadingSelector = state => state.articlesReducer.loading;
```suggestion
const categoryIsLoadingSelector = state => state.articles.loading;
```
Similar to the suggestion above.

2019-04-21 06:33 UTC, valenstical commented on src/styles/shared.scss
> +	padding-top: 100px;
_Hmmmm_, almost every page have this class _.wrapper_ assigned to them. Would adding an extra 50px to the top padding not affect the rest pages.

2019-04-21 06:40 UTC, valenstical approved these changes
LGTM

2019-04-24 00:29 UTC, aanchirinah requested changes
I'm not particularly happy with the file changes regarding styles , it flags too many false postives.

2019-04-24 00:29 UTC, aanchirinah commented on src/components/Category.jsx
> + * @description - returns the home page view
#### Nitpick
- Does it though?

2019-04-24 00:29 UTC, aanchirinah commented on src/components/Category.jsx
> +        {loadingCategory === 'started' ? <PlaceholderLoader /> : <Category begin={0} end={12} articlesCategory={articlesCategory} />}
#### Nitpick
- DRY principle violation fix it.

2019-04-24 00:29 UTC, aanchirinah commented on src/reducers/articleReducer.js
> +    case typeGenerator('SERVER_ERROR'):
#### Nitpick
- Is this really necessary.

2019-04-24 00:29 UTC, aanchirinah commented on src/test/actions/articleCategoryAction.test.js
> +      payload: new Error(),
#### Comment
- Hope this is not a case of editing a test to get yours to pass

2019-04-24 00:29 UTC, aanchirinah commented on src/test/components/Home.test.js
>  configure({ adapter: new Adapter() });
#### Nitpick
- This can be configured to have one instance for all your tests.

2019-04-30 04:38 UTC, valenstical commented
@Andraquin, what is the status of this PR now. Are we done with fixing the merge conflicts?

2019-04-30 04:41 UTC, Andraquin commented
> Hello, @Andraquin, what is the status of this PR now. Are we done with fixing the merge conflicts?

@valenstical Yes I have.

2019-04-30 09:11 UTC, aanchirinah approved these changes

2019-04-30 09:12 UTC, merged